name: Auto Merge on Approval

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if approved
        id: check_approval
        run: echo "approved=${{ github.event.review.state == 'approved' }}" >> $GITHUB_OUTPUT

      - name: Squash merge if approved
        if: steps.check_approval.outputs.approved == 'true'
        run: |
          echo "Head ref: ${{ github.event.pull_request.head.ref  }}"
          git fetch origin ${{ github.event.pull_request.head.ref  }}
          git checkout ${{ github.event.pull_request.head.ref  }}

          git merge --squash ${{ github.event.pull_request.base.ref }}

          git commit -m "${{ github.event.pull_request.title}}"

          git push origin ${{ github.event.pull_request.head.ref  }}

      - name: Auto merge
        if: steps.check_approval.outputs.approved == 'true'
        run: |
          gh pr merge ${{ github.event.number }} --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
