name: Chromatic Deployment

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.stories.tsx'
    types: [opened, edited, reopened]
  push:
    branches:
      - develop
    paths:
      - '**.stories.tsx'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Storybook
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node V2
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true

      - name: Create comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
